# Generated by Django 4.0.8 on 2023-02-03 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import justforfam.core.utils.files.ImageFileCheck
import model_utils.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('text', 'Text'), ('recipe', 'Recipe')], default='text', max_length=255, null=True)),
                ('location', models.CharField(blank=True, choices=[('bedroom', 'Bedroom'), ('living-room', 'Living Room'), ('kitchen', 'Kitchen')], default='bedroom', max_length=255, null=True)),
                ('banner_image', justforfam.core.utils.files.ImageFileCheck.ContentTypeRestrictedFileField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
