# Generated by Django 4.0.8 on 2023-02-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postlocation_remove_textpost_user_textpost_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpost',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.postlocation'),
        ),
    ]
