# Generated by Django 4.0.8 on 2023-02-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '__first__'),
        ('posts', '0003_alter_textpost_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpost',
            name='location',
        ),
        migrations.AddField(
            model_name='textpost',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textpost',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='house.room'),
        ),
        migrations.DeleteModel(
            name='PostLocation',
        ),
    ]
