# Generated by Django 4.0.8 on 2023-02-04 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_house_family_guests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_remove_textpost_location_textpost_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextPost',
            new_name='Post',
        ),
    ]
