# Generated by Django 4.0.8 on 2023-02-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Text')], default='text', max_length=255),
        ),
    ]
