# Generated by Django 4.0.8 on 2023-03-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('posts', '0007_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.album'),
        ),
    ]
