# Generated by Django 4.0.8 on 2023-03-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('posts', '0008_post_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='gallery.album'),
        ),
    ]
