# Generated by Django 4.0.8 on 2023-02-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_room_type_alter_room_privacy_delete_privateroom'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='house.house'),
        ),
    ]
