# Generated by Django 4.0.8 on 2023-02-05 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import rules.contrib.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.ImageField(upload_to='images')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('highlight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_highlight', to='gallery.image')),
                ('images', models.ManyToManyField(blank=True, related_name='image_albums', to='gallery.image')),
            ],
            options={
                'ordering': ['order', '-pk'],
            },
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
    ]
