# Generated by Django 4.0.8 on 2023-02-05 09:43

from django.db import migrations, models
import justforfam.core.utils.files.ImageFileCheck


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_room_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privateroom',
            options={},
        ),
        migrations.AddField(
            model_name='privateroom',
            name='cover_image',
            field=justforfam.core.utils.files.ImageFileCheck.ContentTypeRestrictedFileField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='cover_image',
            field=justforfam.core.utils.files.ImageFileCheck.ContentTypeRestrictedFileField(blank=True, null=True),
        ),
    ]
