# Generated by Django 4.0.8 on 2023-02-05 10:53

from django.db import migrations
import justforfam.core.utils.files.ImageFileCheck


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_alter_privateroom_options_privateroom_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='cover_image',
            field=justforfam.core.utils.files.ImageFileCheck.ContentTypeRestrictedFileField(blank=True, null=True),
        ),
    ]
