# Generated by Django 4.0.8 on 2023-02-12 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0006_house_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='family',
        ),
        migrations.AlterField(
            model_name='house',
            name='family_guests',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_homes', to=settings.AUTH_USER_MODEL),
        ),
    ]
