# Generated by Django 4.0.8 on 2023-02-12 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0007_remove_house_family_alter_house_family_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='family_guests',
        ),
        migrations.AddField(
            model_name='house',
            name='neighbours',
            field=models.ManyToManyField(blank=True, null=True, related_name='neighbours', to=settings.AUTH_USER_MODEL),
        ),
    ]
