# Generated by Django 4.0.8 on 2023-02-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='home',
            new_name='house',
        ),
    ]
